language: julia
julia:
    - 0.4
script:
    - git fetch --unshallow
    - julia --color=yes -e 'Pkg.clone(pwd())'
    - julia --color=yes -e "Pkg.build(\"DSGE\")"
    - julia --check-bounds=yes --color=yes -e "Pkg.test(\"DSGE\")"
